apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  annotations:
    kubernetes.io/description: Contains the configuration for the postgres DB
data:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "todos_db"
  DB_HOST: "localhost"
  DB_VERSION: "16"
  DB_PORT: "5432"