apiVersion: v1
# Once applied you can check it with `kubectl get pvc`
kind: PersistentVolumeClaim
metadata:
  name: todo-db-volume
spec:
  # storageClassName must be one of `kubectl get sc` and it will be dynamically provisioned, 
  # with other values it is expected to be statically provisioned with a PersistentVolume definition
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
