apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-monolith
  template:
    metadata:
      labels:
        app: todo-monolith
    spec:
      containers:
      - image: jaimesalas/lc-todo-monolith
        # Never Since I created the image locally:
        imagePullPolicy: Never
        name: todo-monolith
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 60Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
