apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer
  namespace: nwp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: optimizer
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
      - image: ghcr.io/carloscasalar/night-watch-planner-optimizer:v0.3.1
        name: optimizer
        env:
        - name: PORT
          value: "3000"
        - name: NWP_CLIENT_URL
          value: http://192.168.49.2:30800
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseSerialGC -Xss256k"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
